branch-defaults:
  default:
    environment: Tagroba-env
    group_suffix: null


deploy:
  artifact: www/Archive.zip
global:
  application_name: tagroba
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
